#!/bin/bash
file=/root/.wine/drive_c/users/root/AppData/Local/Amazon/Kindle/kindle.reg
key='HKEY_CURRENT_USER\Software\Wow6432Node\Amazon\Kindle\User Settings'

for (( ok = 1; ok != 0; ))
do
        if [ -f ${file} ]
        then
                wine regedit /C ${file}
        fi
        wine regedit /C ~/autofalse.reg
        wine '/root/.wine/drive_c/Program Files (x86)/Amazon/Kindle/Kindle.exe'
        ok=$?
done

wine regedit /E ${file} "${key}"
